default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: quibble_development

test:
  <<: *default
  database: quibble_test

production:
  adapter: postgresql
  encoding: unicode
  database: quibble_production
  host: localhost
  pool: 5
  username: quibble
  password: <%= ENV["QUIBBLE_DATABASE_PASSWORD"] %>
